version: "3.8"

services:
  api:
    build: .
    container_name: api
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - HISTFILE=/app/log/.bash_history 
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    mem_limit: 256m
    command: -c fsync=off --client-min-messages=warning
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: on-failure
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --maxmemory 500mb --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9090:9090"
    volumes:
      - minio_data:/data
    command: server --console-address ":9090" /data
    healthcheck:
      test: mc ready local
      interval: 2s
      timeout: 5s
      retries: 4
  setup_minio:
    image: minio/mc
    container_name: minio-mc
    depends_on:
      minio:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./spec/fixtures/:/logs
    entrypoint: >
      /bin/sh -c "
      mc config host add minio http://minio:9000 admin 12345678;
      mc mb minio/quake3logs;
      mc anonymous set public minio/quake3logs;
      mc admin config set minio notify_webhook:logcreate endpoint='http://api:3000/uploaded-event' auth_token='some_secure_token' queue_limit='100';
      mc admin service restart minio;
      mc event add minio/quake3logs arn:minio:sqs::logcreate:webhook --event put;
      mc put /logs/double-clean-games.log minio/quake3logs
      exit 0;"

volumes:
  pg_data:
  redis_data:
  minio_data:
  bundle_data:
