default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TechnicalAssessment_development

test:
  <<: *default
  database: TechnicalAssessment_test

production:
  <<: *default
  database: TechnicalAssessment_production
  username: TechnicalAssessment
  password: <%= ENV["TECHNICALASSESSMENT_DATABASE_PASSWORD"] %>
